version: "3"
services:
    netadmin-minio:
        image: minio/minio:latest
        command: server /data --console-address ":9001"
        ports:
            - "9000:9000"
            - "9001:9001"
        restart: always
        container_name: netadmin-minio
        environment:
            TZ: Asia/Shanghai
        volumes:
            - /etc/localtime:/etc/localtime
            - /etc/timezone:/etc/timezone